### ISSUE TITLE
Broken with 1.8 spigot

### ISSUE THREAD

**Issue by 2Fast08** [graywolf336/CasinoSlots#56]
```
[21:20:34] [Server thread/ERROR]: Error occurred while enabling CasinoSlots v2.5.7-b11 (Is it up to date?)
java.lang.NullPointerException
	at com.craftyn.casinoslots.slot.SlotData.getController(SlotData.java:205) ~[?:?]
	at com.craftyn.casinoslots.slot.SlotData.loadSlot(SlotData.java:168) ~[?:?]
	at com.craftyn.casinoslots.slot.SlotData.loadSlots(SlotData.java:107) ~[?:?]
	at com.craftyn.casinoslots.util.ConfigData.load(ConfigData.java:56) ~[?:?]
	at com.craftyn.casinoslots.CasinoSlots.onEnable(CasinoSlots.java:89) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-b8f6402-a646500]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
```

**Comment by graywolf336** [comment]
This means one of the controller blocks which is used no longer exists, I need to do some better error handling.
