### ISSUE TITLE
'NotImplementedException: Code is not implemented' on casino reload.

### ISSUE THREAD

**Issue by mibby** [graywolf336/CasinoSlots#82]
CasinoSlots dev 64

```
[12:07:15] [Server thread/INFO]: player issued server command: /casino reload
[12:07:15] [Server thread/INFO]: [CasinoSlots] Reloading the configs.
[12:07:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'casino' in plugin CasinoSlots v3.0.0-SNAPSHOT-b64
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.jar:git-Paper-1124]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.jar:git-Paper-1124]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:668) ~[patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1424) ~[patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1229) ~[patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.jar:git-Paper-1124]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1124]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.apache.commons.lang.NotImplementedException: Code is not implemented
	at com.craftyn.casinoslots.slot.TypeManager.reloadTypes(TypeManager.java:81) ~[?:?]
	at com.craftyn.casinoslots.command.CasinoReload.process(CasinoReload.java:33) ~[?:?]
	at com.craftyn.casinoslots.command.AnCommandExecutor.onCommand(AnCommandExecutor.java:26) ~[?:?]
	at com.craftyn.casinoslots.CasinoSlots.onCommand(CasinoSlots.java:203) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.jar:git-Paper-1124]
	... 15 more
```

**Comment by graywolf336** [comment]
Thanks for these reports, I've been looking through the current code and it seems like I started coding v3 and never finished it so there's lots of unfinished/incomplete code and features everywhere. Not this week but maybe next week I plan on setting down a few afternoons and planning out a design for the v3 to make it better and easily extensible.

**Comment by mibby** [comment]
Sure, no problem. The only thing I really need for the current v3 branch to be usable is being able to use other types other than 'testing'. :)

**Comment by graywolf336** [comment]
Yeah, I just checked that code out....the types is nowhere near completed, doesn't load anything lol

**Comment by graywolf336** [comment]
The reload piece has been implemented, or at least it won't throw the `NotImplementedException`
